#!/usr/bin/env python3

import os
import re
import sys
import logging
import subprocess
from paver.tasks import main
from paver.easy import *

def preflight_checks(base_path):
    # Ensure that the pre-commit hook is installed
    git_hooks_path = os.path.join(base_path, "../.git", "hooks", "pre-commit")
    install_hook = False
    if os.path.exists(git_hooks_path):
        with open(git_hooks_path, "r") as hook_file:
            hook_content = hook_file.read()
        if "generated by pre-commit" not in hook_content:
            install_hook = True
    else:
        install_hook = True

    if install_hook:
        LOG.warning("⚠️ pre-commit hook is not installed in this repository. Running 'pre-commit install -f'...")
        try:
            subprocess.run(["pre-commit", "install", "-f"], check=True)
        except Exception as e:
            LOG.error(f'❌ Failed to install pre-commit hook: {e}')
            sys.exit(1)


logging.basicConfig(stream=sys.stdout, level=logging.INFO,
                    format=('%(asctime)s %(levelname)-8s '
                            '[%(filename)s:%(lineno)d] %(message)s'),
                    datefmt='%Y/%m/%d %H:%M:%S')

LOG = logging.getLogger(__name__)

if __name__ == '__main__':
    base_path = os.path.dirname(os.path.realpath(__file__))

    preflight_checks(base_path)

    # Use PAVEMENT_FILE env var if set (for testing), otherwise use default
    pavement_file = os.environ.get('PAVEMENT_FILE', f'{base_path}/pavement.py')

    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.argv.insert(1, "-q")
    sys.argv.insert(1, "-f")
    sys.argv.insert(2, pavement_file)
    sys.exit(main())
